build(all): add concurrency to github workflows
awslabs/aws-lambda-powertools-typescript pull request #499
Opened 2022-01-21 15:17 UTC by saragerion

## Description of your changes
This PR adds concurrency limit of 1 to some github workflow. 
This change should prevent race conditions when performing actions over the project.
The behaviour of the affected workflow will be that if one workflow of the same group is already running, the new one will be queued and performed after the old one is done. 

### How to verify this change

This problem happens often when you merge dependabot PRs one after the other, or it can happen with any PR into main.
Allow applicable for e2e tests.

![Screenshot 2022-01-21 at 16 13 51](https://user-images.githubusercontent.com/47529391/150551777-dee05d05-2fcd-41d8-a9ef-f141de564119.png)

### Related issues, RFCs

[#XXXXX](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/XXXXX)  
[#ZZZZZ](https://github.com/awslabs/aws-lambda-powertools-typescript/issues/ZZZZZ)

### PR status

***Is this ready for review?:*** YES  
***Is it a breaking change?:*** NO

## Checklist

- [ ] [My changes meet the tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
- [ ] I have performed a *self-review* of my own code
- [ ] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [ ] I have made corresponding changes to the *documentation*
- [ ] My changes generate *no new warnings*
- [ ] The *code coverage* hasn't decreased
- [ ] I have *added tests* that prove my change is effective and works
- [ ] New and existing *unit tests pass* locally and in Github Actions
- [ ] Any *dependent changes have been merged and published* in downstream module
- [ ] The PR title follows the [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-01-21 15:52 UTC, dreamorosi approved these changes

2022-01-21 15:57 UTC, flochaz requested changes

2022-01-21 15:57 UTC, flochaz commented on .github/workflows/run-e2e-tests.yml
> +      group: e2e-tests
For that one I would prefer we fix the root cause preventing them to run in parrallel : #497

2022-01-25 09:08 UTC, flochaz commented on .github/workflows/run-e2e-tests.yml
> +      group: e2e-tests
Will revert that in a dedicated PR fixing #497

2022-01-25 09:08 UTC, flochaz submitted a review, later dismissed

2022-01-25 09:17 UTC, dreamorosi approved these changes
LGTM & checks are passing

2022-01-25 09:20 UTC, flochaz approved these changes

2022-01-25 09:20 UTC, merged