feat(logger): add e2e tests for logger
awslabs/aws-lambda-powertools-typescript pull request #529
Opened 2022-01-31 21:22 UTC by ijemmy

## Description of your changes

Add e2e tests for logger

Currently, we only have e2e tests for metrics and tracer. This PR adds e2e tests similar to the other two modules. 

### How to verify this change
Run `AWS_PROFILE=<YOUR_PROFILE_NAME> AWS_REGION=eu-central-1 npx jest --group=e2e/logger/`

Here's the output:
```
Test Suites: 3 passed, 3 of 8 total
Tests:       13 passed, 13 total
Snapshots:   0 total
Time:        114.482 s
```

### Related issues, RFCs

https://github.com/awslabs/aws-lambda-powertools-typescript/issues/353 

### PR status

***Is this ready for review?:*** NO  
***Is it a breaking change?:*** NO

## Checklist

- [x] [My changes meet the tenets criteria](https://awslabs.github.io/aws-lambda-powertools-python/#tenets)
- [x] I have performed a *self-review* of my own code
- [x] I have *commented* my code where necessary, particularly in areas that should be flagged with a TODO, or hard-to-understand areas
- [x] I have made corresponding changes to the *documentation*
- [x] My changes generate *no new warnings*
- [x] The *code coverage* hasn't decreased
- [x] I have *added tests* that prove my change is effective and works
- [x] New and existing *unit tests pass* locally and in Github Actions
- [x] Any *dependent changes have been merged and published* in downstream module
- [x] The PR title follows the [conventional commit semantics](https://github.com/awslabs/aws-lambda-powertools-typescript/blob/main/.github/semantic.yml#L2)

### Breaking change checklist

- [ ] I have documented the migration process
- [ ] I have added, implemented necessary warnings (if it can live side by side)

---

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2022-02-01 08:05 UTC, flochaz requested changes
LGTM except cdk link

2022-02-01 08:50 UTC, dreamorosi requested changes
Already looking good!

Just left some comments on the files, plus this one:
- Some files contain a copyright notice while others don't, the rest of the project also doesn't contain any so we should settle on one

2022-02-01 08:50 UTC, dreamorosi commented on packages/logger/tests/helpers/InvocationLog.ts
> +   *      '2022-01-27T16:04:39.323Z\tafb6de1a-48f8-4fbb-ad72-23a4f0c2924c\tINFO\t{"cold_start":true,"function_arn":"arn:aws:lambda:eu-central-1:561912387782:function:loggerMiddyStandardFeatures-c555a
Can we use the same ARNs we have [in the docs](https://awslabs.github.io/aws-lambda-powertools-typescript/latest/core/logger/#capturing-lambda-context-info)?

2022-02-01 08:50 UTC, dreamorosi commented on packages/logger/tests/e2e/basicFeatures.middy.test.ts
> +      // We will extract the last part
Could you elaborate more on these comments? From the way it reads it seems a line is missing

2022-02-01 15:24 UTC, dreamorosi submitted a review, later dismissed

2022-02-01 15:38 UTC, dreamorosi reviewed
Just ran the e2e tests [here on GitHub](https://github.com/awslabs/aws-lambda-powertools-typescript/runs/5023529706) and it failed, it seems there are issues with the stack deployment based on the errors.

2022-02-11 15:15 UTC, ijemmy commented
@dreamorosi Logger uses `eu-central-1` for unit test. I need to CDK bootstrap the region.

I am considering changing everything to `eu-west-1`. But that will affect unit testing so I will discuss with @saragerion  first.

2022-02-14 11:10 UTC, dreamorosi approved these changes

2022-02-15 09:43 UTC, flochaz approved these changes
LGTM !

2022-02-15 09:47 UTC, merged

2022-02-15 10:05 UTC, ijemmy commented
fyi, 1 check didn't pass (e2e) test.

It's a flaky test from metric, not logger. I have rerun and everything is green https://github.com/awslabs/aws-lambda-powertools-typescript/actions/runs/1846184047